### ISSUE TITLE
Help setting up

### ISSUE THREAD

**Issue by willpriceb** [k-labs/docker-forgetproxy#2]
Hi,

I'm trying to set this up from behind a corporate network without a global DNS server available. I'm trying to set up redsocks with `dnstc` so that DNS queries go over tcp instead of udp. I've augmented the `redsocks` script with a few new iptables rules, so far I've got:

``` sh
iptables_rules() {
    # private ip ranges are not intercepted
    iptables -t nat -$1 PREROUTING -i docker0 -d 10.0.0.0/8 -j RETURN
    iptables -t nat -$1 PREROUTING -i docker0 -d 127.0.0.0/8 -j RETURN
    iptables -t nat -$1 PREROUTING -i docker0 -d 169.254.0.0/16 -j RETURN
    iptables -t nat -$1 PREROUTING -i docker0 -d 172.16.0.0/12 -j RETURN
    iptables -t nat -$1 PREROUTING -i docker0 -d 192.168.0.0/16 -j RETURN
    iptables -t nat -$1 PREROUTING -i docker0 -d 224.0.0.0/4 -j RETURN
    iptables -t nat -$1 PREROUTING -i docker0 -d 240.0.0.0/4 -j RETURN

    iptables -t nat -$1 PREROUTING -p udp --dport 53   -i docker0 -j REDIRECT --to 5300 2>/dev/null
    iptables -t nat -$1 PREROUTING -p tcp --dport 80   -i docker0 -j REDIRECT --to 12345 2>/dev/null
    iptables -t nat -$1 PREROUTING -p tcp --dport 8080 -i docker0 -j REDIRECT --to 12345 2>/dev/null
    iptables -t nat -$1 PREROUTING -p tcp -i docker0 -j REDIRECT --to 12346
}
```

I try and run redsocks with:
`docker build -t willp/forgetproxy .`
`docker run -it --net=host --privileged -e http_proxy=http://wasp.gbr.iae.net:3128 -e https_proxy=http://wasp.gbr.iae.net:3128 -it willp/forgetproxy`

Once up, I then test out the network with
`docker run --rm -it ubuntu apt-get update`

I've been watching packets on wireshark and the ubuntu box is trying to use google's dns servers which doesn't work. I think I need to use the `--dns` option to point it towards the redsocks box but haven't had much luck does this yet, I've tried using `--dns 172.17.46.1` where the ip is that of my `docker0` instance but I assume this ends up getting caught by one of the earlier iptables rules and doesn't get redirected to port 5300... any ideas?

**Comment by benoitvidis** [comment]
Hi,

Maybe by reordering your iptables rules?

``` bash
iptables_rules() {
    iptables -t nat -$1 PREROUTING -p udp --dport 53   -i docker0 -j REDIRECT --to 5300 2>/dev/null

    # private ip ranges are not intercepted
    iptables -t nat -$1 PREROUTING -i docker0 -d 10.0.0.0/8 -j RETURN
    iptables -t nat -$1 PREROUTING -i docker0 -d 127.0.0.0/8 -j RETURN
    iptables -t nat -$1 PREROUTING -i docker0 -d 169.254.0.0/16 -j RETURN
    iptables -t nat -$1 PREROUTING -i docker0 -d 172.16.0.0/12 -j RETURN
    iptables -t nat -$1 PREROUTING -i docker0 -d 192.168.0.0/16 -j RETURN
    iptables -t nat -$1 PREROUTING -i docker0 -d 224.0.0.0/4 -j RETURN
    iptables -t nat -$1 PREROUTING -i docker0 -d 240.0.0.0/4 -j RETURN

    iptables -t nat -$1 PREROUTING -p tcp --dport 80   -i docker0 -j REDIRECT --to 12345 2>/dev/null
    iptables -t nat -$1 PREROUTING -p tcp --dport 8080 -i docker0 -j REDIRECT --to 12345 2>/dev/null
    iptables -t nat -$1 PREROUTING -p tcp -i docker0 -j REDIRECT --to 12346
}
```

**Comment by willpriceb** [comment]
No luck, the packets look the same on wireshark. I try setting the DNS server in the non proxy-aware container to googles DNS servers (in the hope that redsocks will forward them to the proxy which has internet access). The requests look good, they're directed to 172.17.42.1, docker0's IP address, but then I get ICMP responses saying that 8.8.8.8 is unavailable, redsocks with debug flags enabled doesn't show anything.

I wrote a bit more about the setup here: 
http://stackoverflow.com/questions/32953878/docker-redsocks-proxy-behind-http-proxy-with-no-internet-dns

Thank you very much for you help--much appreciated!
EDIT: I should have noted that I'm using an ubuntu guest inside Virtualbox on OS X.

**Comment by benoitvidis** [comment]
Ok, I looked a bit further in redsocks documentation.

If I understand properly, the dnstc just forces the client to send the request again using a TCP connection that then can be intercepted by redsocks.

In your case, it may be that you are missing this tcp redirection step:

``` bash
iptables_rules() {
    iptables -t nat -$1 PREROUTING -p udp --dport 53   -i docker0 -j REDIRECT --to 5300 2>/dev/null
    iptables -t nat -$1 PREROUTING -p tcp --dport 53   -i docker0 -j REDIRECT --to 12346 2>/dev/null

    # private ip ranges are not intercepted
    iptables -t nat -$1 PREROUTING -i docker0 -d 10.0.0.0/8 -j RETURN
    iptables -t nat -$1 PREROUTING -i docker0 -d 127.0.0.0/8 -j RETURN
    iptables -t nat -$1 PREROUTING -i docker0 -d 169.254.0.0/16 -j RETURN
    iptables -t nat -$1 PREROUTING -i docker0 -d 172.16.0.0/12 -j RETURN
    iptables -t nat -$1 PREROUTING -i docker0 -d 192.168.0.0/16 -j RETURN
    iptables -t nat -$1 PREROUTING -i docker0 -d 224.0.0.0/4 -j RETURN
    iptables -t nat -$1 PREROUTING -i docker0 -d 240.0.0.0/4 -j RETURN

    iptables -t nat -$1 PREROUTING -p tcp --dport 80   -i docker0 -j REDIRECT --to 12345 2>/dev/null
    iptables -t nat -$1 PREROUTING -p tcp --dport 8080 -i docker0 -j REDIRECT --to 12345 2>/dev/null
    iptables -t nat -$1 PREROUTING -p tcp -i docker0 -j REDIRECT --to 12346
}
```

Without the second line, the TCP DNS request is caught by the private ip range exclusion block and sent as-is to the original DNS server, being Google one in this case.

**Comment by benoitvidis** [comment]
Ok, sorry, you can forget the last comment.

Here is my generated redocks.conf file:

```
base {
  log_debug = off;
  log_info = on;
  log = "stderr";
  daemon = off;
  user = redsocks;
  group = redsocks;
  redirector = iptables;
}

dnstc {
    // fake and really dumb DNS server that returns "truncated answer" to
    // every query via UDP, RFC-compliant resolver should repeat same query
    // via TCP in this case.
    local_ip = 0.0.0.0;
    local_port = 5300;
}
redsocks {
  type = http-relay;
  ip = 10.34.6.100;
  port = 3128;
  local_ip = 0.0.0.0;
  local_port = 12345;
}
redsocks {
  type = http-connect;
  ip = 10.34.6.100;
  port = 3128;
  local_ip = 0.0.0.0;
  local_port = 12346;
}
```

And my iptables rules:

```
    iptables -t nat -$1 PREROUTING -p udp --dport 53   -i docker0 -j REDIRECT --to 5300 2>/dev/null

    # private ip ranges are not intercepted
    iptables -t nat -$1 PREROUTING -i docker0 -d 10.0.0.0/8 -j RETURN
    iptables -t nat -$1 PREROUTING -i docker0 -d 127.0.0.0/8 -j RETURN
    iptables -t nat -$1 PREROUTING -i docker0 -d 169.254.0.0/16 -j RETURN
    iptables -t nat -$1 PREROUTING -i docker0 -d 172.16.0.0/12 -j RETURN
    iptables -t nat -$1 PREROUTING -i docker0 -d 192.168.0.0/16 -j RETURN
    iptables -t nat -$1 PREROUTING -i docker0 -d 224.0.0.0/4 -j RETURN
    iptables -t nat -$1 PREROUTING -i docker0 -d 240.0.0.0/4 -j RETURN

    iptables -t nat -$1 PREROUTING -p tcp --dport 80   -i docker0 -j REDIRECT --to 12345 2>/dev/null
    iptables -t nat -$1 PREROUTING -p tcp --dport 8080 -i docker0 -j REDIRECT --to 12345 2>/dev/null
    iptables -t nat -$1 PREROUTING -p tcp -i docker0 -j REDIRECT --to 12346
```

Using opendns servers:

```
docker --rm --dns=208.67.222.222 -it ubuntu bash
root@ce969b3fd65d:/# nslookup google.com                                                                                                                                                                                                     
;; Truncated, retrying in TCP mode.
Server:         208.67.222.222
Address:        208.67.222.222#53

Non-authoritative answer:
Name:   google.com
Address: 216.58.211.78
```

_but_

```
root@ce969b3fd65d:/# curl "http://google.com"
curl: (6) Could not resolve host: google.com
```

So it looks the solution works as expected except the fact that the DNS request is not sent again using TCP when using libc resolver. This can be checked looking at redsocks output.

I tried to add `options use-vc` to the container resolv.conf file. When doing so, I can see the traffic going through redsocks to opendns servers but curl or apt are still unable to resolve any domain. Even if this solution would work, it is not agnostic from docker side anymore.

I did not check but I suppose it should be possible to set a DNS server inside a container that would forward the DNS requests through redsocks. According to [this post](http://serverfault.com/questions/348399/force-forwarder-dns-requests-to-tcp-mode), bind9 does retry using TCP mode.

Hope it helps

**Comment by willpriceb** [comment]
Hi @benoitvidis,

I'm sorry for my late response, work got in the way. Thanks very much for the response, I've managed to replicate your set up and am now able to use nslookup to resolve server names! I'm going to have a bash at creating an environment that utilises a BIND server with redsocks to transparently proxy on my network.
